name: twitter_frontend_react_actions
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --force
      - name: build project
        run: npm run build
      - name: run __tests__
        run: npm run test
#  build_and_pub:
#    needs: init
#    runs-on: ubuntu-latest
#    env:
#      LOGIN: ${{ secrets.DOCKER_LOGIN }}
#      NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
#    steps:
#      - name: Login to Docker
#        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
#      - uses: actions/checkout@master
#      - name: Build image
#        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
#      - name: Push image to docker
#        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}